pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Refresh banners and zones') {
            failFast true
            parallel {
                stage('Refresh banners cache') {
                    steps {
                        build job: "banners_cache_refresh_$ENVIRONMENT", wait: true
                    }
                }
                stage('Refresh zones cache') {
                    steps {
                        build job: "zones_cache_refresh_$ENVIRONMENT", wait: true
                    }
                }
            }
        }
        stage('Test') {
            parallel {
                stage('Domain Targeting tests') {
                    steps {
                        script {
                            try {
                                sh 'mvn test -Dtest=steps.DomainTargetingTest -P $ENVIRONMENT'
                                currentBuild.result = 'SUCCESS'
                            } catch (Exception ex) {
                                currentBuild.result = 'FAILURE'
                            }
                        }
                    }
                }
                stage('UDMP tests') {
                    steps {
                        script {
                            try {
                                sh 'mvn test -Dtest=steps.UDMPTest -P $ENVIRONMENT'
                                currentBuild.result = 'SUCCESS'
                            } catch (Exception ex) {
                                currentBuild.result = 'FAILURE'
                            }
                        }
                    }
                }
                stage('Server Programmatic tests') {
                    steps {
                        script {
                            try {
                                sh 'mvn test -Dtest=steps.ServerProgrammaticTest -P $ENVIRONMENT'
                                currentBuild.result = 'SUCCESS'
                            } catch (Exception ex) {
                                currentBuild.result = 'FAILURE'
                            }
                        }
                    }
                }
                stage('Server Programmatic tests') {
                    steps {
                        script {
                            try {
                                sh 'mvn test -Dtest=steps.ServerProgrammaticTest -P $ENVIRONMENT'
                                currentBuild.result = 'SUCCESS'
                            } catch (Exception ex) {
                                currentBuild.result = 'FAILURE'
                            }
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            junit 'target/surefire-reports/*.xml'
            cleanWs()
        }
    }
}